name: main-ci
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm install pnpm -g
        pnpm install
        pnpm build
        
      # 部署到 GitHub Pages
    - name: Deploy
      # 使用别人写好的一个 action
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
        token: ${{ secrets.token }}
        # 打包后的文件部署到哪个分支上
        BRANCH: gh-pages
        # 打包后的文件在哪里
        FOLDER: dist
